# Generated by Django 4.2.5 on 2023-09-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_userinfo_create_time_alter_userinfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='School Name')),
                ('district', models.SmallIntegerField(choices=[(1, 'Wan Chai'), (2, 'Central and Western'), (3, 'Sai Kung'), (4, 'Eastern'), (5, 'Southern'), (6, 'Tsuen Wan'), (7, 'North'), (8, 'Kowloon City'), (9, 'Yau Tsim Mong'), (10, 'Sha Tin'), (11, 'Islands'), (12, 'Yuen Long'), (13, 'Tai Po'), (14, 'Wong Tai Sin'), (15, 'Tuen Mun'), (16, 'Kwai Tsing'), (17, 'Sham Shui Po'), (18, 'Kwun Tong')], verbose_name='District')),
                ('status', models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Promoted')], verbose_name='Status')),
            ],
        ),
    ]
