# Generated by Django 4.2.5 on 2023-09-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_schoolinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Promoted')], verbose_name='Status'),
        ),
    ]
