# Generated by Django 4.1.7 on 2023-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('year', models.SmallIntegerField(choices=[(1, '2012'), (2, '2013'), (3, '2014'), (4, '2015'), (5, '2016'), (6, '2017'), (7, '2018'), (8, '2019'), (9, '2020'), (10, '2021'), (11, '2022'), (12, '2023')])),
            ],
        ),
    ]
